### ISSUE TITLE
Last typed word becomes invisible on typing a space, comma or dot ( . ).

### ISSUE THREAD

**Issue by itsaky** [Rose2073/CodeEditor#1]
I added the repo in my project as written in Readme. I had to override the chars() and codePoints() method in com.rose.editor.common.Content class (I had to override it because I got a error saying that I should implement the inherited abstract methods).

All things work fine except when I type a space, comma or a dot ( . )

I'm using [AIDE](https://play.google.com/store/apps/details?id=com.aide.ui)  to compile and run the project.

Any help or guidance is appreciated.

**Comment by Rose2073** [comment]
I build this project on AIDE as well.
The unimplemented methods are required to be implemented for higher Android SDK version, but if you use older Android SDK or use AndroidStudio, this annoying error will be gone.
I used android.jar of Android API 21 in AIDE.  When it comes to higher SDK version, AIDE generates errors for these methods.
This project is tested on Android 7.1.1 and I did not find your problems.
I will try to test the problems you memtioned and implement these methods officially soon.
Thank you for your issue and if you find out what caused the problem, please concat me at once.

**Comment by itsaky** [comment]
**Okay! Thanks.**
I hope you fix the issue and update the repository soon.

**Comment by Rose2073** [comment]
Thank you for your gif. This helps me a lot.
I've already found out where the problem probably is.

This is most probably because my editor does not really adapt your input method's word auto complete. And I think if you close word auto completion, the editor will work well.
To solve to problem, I will change the way my InputConnection works.

If convenient, could you please send your input method to my email(2073412493@qq.com) due to research?
Thanks.

**Comment by itsaky** [comment]
**You are right!** Turning off suggestions and auto-completion did the work.

**Comment by Rose2073** [comment]
I've got your email but I was unable to reply. 

I'm sorry about my poor English. What I meant is that I need the application which you used to compose text. 
Thanks very much if you can send it to me :)
I'll fix the bug soon!

**Comment by itsaky** [comment]
I'm using [Gboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin)

Btw, as you pointed out, I added two flags (EditorInfo.TYPE_TEXT_FLAG_NO_SUGGESTIONS|EditorInfo.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD) in onCreateInputConnection on com.rose.editor.android.RoseEditor class. This solves the problem for me.

Thanks for the help...

**Comment by Rose2073** [comment]
Thanks for your feedback.
I will try to adapt Gboard's auto-completion soon.
